# Local PostgreSQL — database is auto-created by LocalDatabaseConfig on startup
spring.datasource.url=jdbc:postgresql://localhost:5432/str_db
spring.datasource.username=postgres
spring.datasource.password=kodelab213
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.contexts=local
spring.jpa.show-sql=true
logging.level.com.str.backend=DEBUG
logging.level.liquibase=INFO
